### PR TITLE
Add POM for maven support

### PR DESCRIPTION
**Pull request by kerbymart**
Initial pom to be able to import project as maven and do $mvn clean install

### CODE REVIEW

**Comment by phil-brown** [comment]
@kerbymart I am not very familiar with how to add support for maven. Can you point me at some more resources so that I can understand this better?

**Comment by void256** [comment]
:+1:

**Comment by phil-brown** [comment]
I've begun adding support for Maven - including adding a pom.xml file and modifying the way the project is configured. This is currently being done in the [develop branch](https://github.com/phil-brown/jCSS-Parser/tree/develop). @kerbymart would this suffice for starts? I am also looking into what is required to include this in Maven Central via SonaType.

**Comment by kerbymart** [comment]
@phil-brown my experience is with deploying with Bintray/JFrog which seems to be easier like this:

```
<repositories>
    <!-- Snapshot repository -->
    <repository>
        <id>oss-jfrog-artifactory-snapshots</id>
        <name>oss-jfrog-artifactory-snapshots</name>
        <url>http://oss.jfrog.org/artifactory/oss-snapshot-local</url>
    </repository>
</repositories>
```

**Comment by phil-brown** [comment]
I've submitted a maven ticket to OSSRH, so hopefully this will be easier to add to projects very soon.

**Pull request closed without merging**
